Contracts/IVideoRepository.cs
Entities/Data/Video/VideoListDto.cs
MojeWidelo_WebApi/Controllers/VideoController.cs
Repository/VideoRepository.cs

jak testować?
musimy mieć jakiegoś usera, który jest twórcą oraz ma wrzucone jakieś filmy (proponuje parę publicznych i parę prywatnych - jak to zrobić to chyba nie w tym poradniku ;pp)
teraz robimy 2 testy:
`https://localhost:7004/api/user/videos?id=6430ca6a3a1f14832a8e7df3`, gdzie id to id twórcy, którego filmy chcemy pobrać, w autoryzacji podajemy TOKEN AUTORA - powinno nam zwrócić tablicę wszystkich metadanych filmów - WSZYSTKICH
drugi test - taki sam request, ale z tokenem INNEGO użytkownika - zwróci tablicę z filmami TYLKO PUBLICZNYMI
koniec testu, pozdrawiam ELDON
unit testy dodam jak saj założy testy do video

MW-169 Get all videos from user by user id

---

Contracts/IRepositoryBase.cs
Contracts/IRepositoryWrapper.cs
Contracts/ISubscriptionsRepository.cs
Contracts/IVideoRepository.cs
Entities/Data/Subscription/SubscriptionDto.cs
Entities/Data/Subscription/SubscriptionListDto.cs
Entities/Models/Subscription.cs
Entities/Utils/DatabaseSettings.cs
Entities/Utils/IDatabaseSettings.cs
MojeWidelo_WebApi.UnitTests/Mocks/MockIRepositoryWrapper.cs
MojeWidelo_WebApi.UnitTests/Mocks/MockISubscriptionsRepository.cs
MojeWidelo_WebApi.UnitTests/Mocks/MockIUsersRepository.cs
MojeWidelo_WebApi.UnitTests/Tests/Controllers/BaseControllerTests.cs
MojeWidelo_WebApi.UnitTests/Tests/Controllers/SubscriptionsControllerTests.cs
MojeWidelo_WebApi.UnitTests/Tests/Controllers/UsersControllerTests.cs
MojeWidelo_WebApi.UnitTests/Tests/Managers/SubscriptionsManagerTests.cs
MojeWidelo_WebApi.UnitTests/Tests/Managers/UsersManagerTests.cs
MojeWidelo_WebApi.UnitTests/Tests/Repositories/SubscriptionsRepositoryTests.cs
MojeWidelo_WebApi.UnitTests/Tests/Repositories/UsersRepositoryTests.cs
MojeWidelo_WebApi/Controllers/SubscriptionsController.cs
MojeWidelo_WebApi/Controllers/VideoController.cs
MojeWidelo_WebApi/Extensions/ServiceExtensions.cs
MojeWidelo_WebApi/Mapper/SubscriptionProfile.cs
MojeWidelo_WebApi/Mapper/VideoProfile.cs
MojeWidelo_WebApi/appsettings.json
Repository/Managers/SubscriptionsManager.cs
Repository/RepositoryWrapper.cs
Repository/SubscriptionsRepository.cs
Repository/VideoRepository.cs

endpointy GET, POST, DELETE do subskrypcji + testy (pokrycie 100%)
Jira task: https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-177
+ endpoint do pobierania filmow od zasubowanych kanałów:
https://mojewideo.atlassian.net/browse/MW-178
dodatkowo: 
- poprawienie mapowania przy zwracaniu upload video metadata
- update'owanie danych usera (czyli wsm samego nickname) przy get video-metadata, bo trzymamy tam dane usera ktore się mogą zmienić poprzez edycję. I tak trzeba tam edytować obiekt metadata bo trzeba podbić viewCounter, więc przy okazji aktualizuję też nickname w razie jakby się zmienił
testowanie: front na branchu `MW-179/subscribing`

MW-177/subscriptions

---

Entities/Data/Video/VideoListDto.cs
MojeWidelo_WebApi/Controllers/VideoController.cs

Poprawka response body, było niezgodnie ze specyfikacją

Fix user/videos/subscribed response

---

Contracts/ICommentRepository.cs
Entities/Models/Comment.cs
Entities/Models/User.cs
MojeWidelo_WebApi/Controllers/CommentController.cs
Repository/CommentRepository.cs
Repository/Managers/CommentManager.cs
Repository/ReactionRepository.cs

Comment responses functionality

MW-174/Komentarze-odpowiedzi

---

MojeWidelo_WebApi/Controllers/CommentController.cs

playlists fix

---

Entities/Data/Playlist/PlaylistBaseDto.cs

https://mojewideo.atlassian.net/browse/MW-208

MW-208 Fix missing data in playlist/user

---

Contracts/IRepositoryBase.cs
Contracts/IUsersRepository.cs
Contracts/IVideoRepository.cs
MojeWidelo_WebApi/Controllers/SubscriptionsController.cs
MojeWidelo_WebApi/Controllers/VideoController.cs
MojeWidelo_WebApi/Extensions/ServiceExtensions.cs
Repository/CommentRepository.cs
Repository/Managers/VideoManager.cs
Repository/PlaylistRepository.cs
Repository/ReactionRepository.cs
Repository/RepositoryBase.cs
Repository/SubscriptionsRepository.cs
Repository/UsersRepository.cs
Repository/VideoRepository.cs

Jira: https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-195
Problem:

Fix views and subscriptions counters

---

Contracts/IPlaylistRepository.cs
Contracts/IVideoRepository.cs
Entities/Data/Interfaces/ISearchable.cs
Entities/Data/Playlist/PlaylistBaseDto.cs
Entities/Data/Search/SearchResultDto.cs
Entities/Data/User/UserDto.cs
Entities/Data/Video/VideoMetadataDto.cs
Entities/Entities.csproj
Entities/Enums/SortingCriterion.cs
Entities/Enums/SortingType.cs
MojeWidelo_WebApi/Controllers/SearchController.cs
MojeWidelo_WebApi/Extensions/ServiceExtensions.cs
MojeWidelo_WebApi/MojeWidelo_WebApi.csproj
MojeWidelo_WebApi/Program.cs
Repository/Managers/SearchManager.cs
Repository/PlaylistRepository.cs
Repository/Repository.csproj
Repository/VideoRepository.cs

znalazłem bibliotekę do wyszukiwania rozproszonego, więc np. jak wpiszemy "nrobb" to wyszuka się użytkownik "norb", albo "tturoial" dopasuje "tutorial". Są 4 poziomy dokładności dopasowania, na razie ustawiłem drugi pod względem restrykcyjności
użytkownicy są szukani tylko po nicku
playlisty są szukane tylko po nazwie
filmy sa szukane po:
- tytule
- nicku autora
- tagach
JAK TESTOWAĆ:
zapytanie w postmanie w katalogu mikołaj -> search

MW-201 Add endpoint for searching users, videos and playlists

---

Contracts/IUsersRepository.cs
Entities/Data/User/UserDto.cs
Entities/Models/User.cs
MojeWidelo_WebApi/Controllers/DonateController.cs
MojeWidelo_WebApi/Controllers/UsersController.cs
Repository/UsersRepository.cs

eldon,
na początku pragnę zaznaczyć, że chyba lepiej zamienić AccountBalance na decimal, a nie double, bo już zauważyłem błędy zaokrągleń
po drugie, wszystko na razie jest w user repository/controller, jeżeli będzie potrzeba zmienić to jutro pod okiem szefa backendu, mikołaja, refactor
JAK TESTOWAĆ:
POST `/api/donate/send`
w query podajemy 2 parametry:
* `id` osoby, której chcemy wpłacić bilon
* `amount` czyli hajsik do przelania
co przetestować:
- jeżeli taki user jakiego id podamy nie istnieje, to 404
- jeżeli taki user nie jest twórcą, to 400
- jeżeli wszystko git, to 200 i sprawdzamy w bazie, czy AccountBalance tego usera się zwiększył
POST `/api/donate/withdraw`
w query podajemy 1 parametr:
* `amount`, czyli tyle, ile chcemy wypłacić
co przetestować:
- jeżeli nie jesteśmy twórcą, to …

Add donating and withdrawing money (virtual)

---

Contracts/IRepositoryBase.cs
Contracts/IUsersRepository.cs
Contracts/IVideoRepository.cs
MojeWidelo_WebApi/Controllers/ImageController.cs
MojeWidelo_WebApi/Controllers/SearchController.cs
MojeWidelo_WebApi/Controllers/UsersController.cs
MojeWidelo_WebApi/Controllers/VideoController.cs
Repository/Managers/UsersManager.cs
Repository/Managers/VideoManager.cs
Repository/RepositoryBase.cs
Repository/UsersRepository.cs
Repository/VideoRepository.cs

eldon,
poprawki wlatują, a w nich:
* to co było w miniaturkach dodane do avatarów
* usunięcie warningów
* uri dostawane w locie (w get) a nie trzymane w bazie (w post i w put)
* dodanie asynchroniczności
* przeniesienie powtarzalnego kodu do klasy niżej
* nazwa pliku inna niż temp
* try-catche
I WIELE INNYCH!
potężny pr, przetestowałem w postmanie, ale najlepiej chyba będzie to testować z frontem
od razu mówię, że wywali wam wszystkie obecne miniaturki i avatary, trzeba put, albo założyć nowe konto/dodać nowy film
elDON, DONbranoc
@nowakmikolaj możesz zobaczyć, czy rozwiązałem wszystkie twoje wątpliwości ze starego PR do miniaturek https://github.com/IO2-2023-JB/team-10-backend/pull/21

Add fixes to images (avatar + thumbnail)

---

Repository/VideoRepository.cs

zmiana AC3 -> MP3
@nizioleque testował i działa

Audio codec AC3 -> MP3

---

Repository/VideoRepository.cs

Teraz 'duration' zgodnie z dokumentacją jest

Fix duration format (as per documentation)

---

MojeWidelo_WebApi/Controllers/UsersController.cs

Jak w tytule
Endpointy do testowania są w Postman -> saj

[MW-192] Creator has to delete all videos before being able to change to basic

---

Contracts/IHistoryRepository.cs
Entities/Models/History.cs
MojeWidelo_WebApi/Controllers/VideoController.cs
Repository/HistoryRepository.cs

naprawa licznika wyświetleń.
nowe wyświetlenie nabijane jest dopiero po 30s od ostatniego wyświetlenia.
jak testować -> no pewnie najlepiej na froncie, bo w postmanie to można K* dostać :)
pzdr.

Fix bug in view counter

---

MojeWidelo_WebApi/Controllers/ImageController.cs
Repository/Managers/ImagesManager.cs

TROCHĘ JESTEM DEBILEM
bo przy PRze który był od kompresowania zdjęć zapisywałem je w PNG zamiast w JPEG - zajebista kompresja XD
więc krótka poprawka (A ZDJĘCIA ZAJMUJĄ 5!!!!!!! RAZY MNIEJ MIEJSCA)

Change format of stored images to JPEG

---

Entities/Data/Comment/CommentDto.cs
MojeWidelo_WebApi/Controllers/CommentController.cs

MW-249 Adjust comment-related endpoints to specification

---

MojeWidelo_WebApi/Controllers/SubscriptionsController.cs
MojeWidelo_WebApi/Extensions/ServiceExtensions.cs
MojeWidelo_WebApi/Filters/ObjectIdValidationFilter.cs
MojeWidelo_WebApi/Filters/RenameParameterFilter.cs

niezgodność nazw parametrów ze specyfikacją

Fix parameter names in POST and DELETE subscription

---

Contracts/IRepositoryWrapper.cs
Contracts/ITicketRepository.cs
Entities/Data/Ticket/RespondToTicketDto.cs
Entities/Data/Ticket/SubmitTicketDto.cs
Entities/Data/Ticket/SubmitTicketResponseDto.cs
Entities/Enums/TicketStatus.cs
Entities/Enums/TicketTargetTypeDto.cs
Entities/Models/Ticket.cs
Entities/Utils/DatabaseSettings.cs
Entities/Utils/IDatabaseSettings.cs
MojeWidelo_WebApi/Controllers/TicketController.cs
MojeWidelo_WebApi/Extensions/ServiceExtensions.cs
MojeWidelo_WebApi/Mapper/TicketProfile.cs
MojeWidelo_WebApi/appsettings.json
Repository/RepositoryWrapper.cs
Repository/TicketRepository.cs

Create env for tickets, add put & post

---

Contracts/ITicketRepository.cs
Entities/Data/Ticket/GetTicketDto.cs
Entities/Data/Ticket/GetTicketStatusDto.cs
MojeWidelo_WebApi/Controllers/CommentController.cs
MojeWidelo_WebApi/Controllers/TicketController.cs
MojeWidelo_WebApi/Mapper/TicketProfile.cs
Repository/TicketRepository.cs

MW-238 Ticket GETs

---

MojeWidelo_WebApi/Controllers/PlaylistController.cs
MojeWidelo_WebApi/Controllers/SearchController.cs
MojeWidelo_WebApi/Controllers/VideoController.cs
Repository/VideoRepository.cs

MW-248
już nigdzie nie powinny się wyświetlać video z processing progressem innym niż ready
jak coś przegapiłem to SORY
eldon.

Add filtering videos by processing progress

---

Contracts/ICommentRepository.cs
MojeWidelo_WebApi/Controllers/CommentController.cs
MojeWidelo_WebApi/Controllers/VideoController.cs
Repository/CommentRepository.cs

elDON
na wejście 2. i 5. zrobione (z nowej numeracji z jiry)

Mw 263/saj sosna/fix/deleting

---

Repository/Managers/VideoManager.cs
Repository/VideoRepository.cs

Działa
Przetestowałem na lokalu
Screen z dowodem na grupie
testy na postmanie moim

[MW-263] Fix logic in playlist/video

---

Contracts/IVideoRepository.cs
Entities/Data/Playlist/RecommendationDto.cs
Entities/Utils/Variables.cs
MojeWidelo_WebApi.UnitTests/Tests/Controllers/PlaylistControllerTests.cs
MojeWidelo_WebApi.UnitTests/Tests/Controllers/VideoControllerTests.cs
MojeWidelo_WebApi/Controllers/PlaylistController.cs
MojeWidelo_WebApi/appsettings.Production.json
MojeWidelo_WebApi/appsettings.json
Repository/Managers/VideoManager.cs
Repository/VideoRepository.cs

https://github.com/IO2-2023-JB/team-10-backend/pull/67
Zadresowanie sugestii z tego PRa, których nie udało się wprowadzić przed review S5

[MW-240] recommendation endpoint overdue fixes

---

MojeWidelo_WebApi/Filters/VideoExtensionValidationFilter.cs

Przetestowane na plikach 
Działa, wyniki na tg

[MW-262] Accept .MOV as a valid video format

---

Repository/VideoRepository.cs

Bug z MW-266 + dodałem żeby w rekomendacjach nie pojawiały się filmiki użytkownika

[MW-266] Videos recommended won't be own videos or will they be private
